### ISSUE TITLE
Ventanas admin (clientes registrados,  pagos realizados)

### ISSUE THREAD

**Issue by Andres2020-CESW2** [Andres2020-CESW2/CESW2#6]
Realizar funcionalidad CRUD en clientes registrados.
Listar datos de la BD (pagos realizados)
Funcionalidades front (buscar datos, desplegar opciones al seleccionar fila)

**Comment by Kevin-A20** [comment]
Se realiza tarea de funcionalidad de las paginas correspondientes al admin.
